#!/usr/bin/env python
#
#   ui/wscript
#
#	This is part of Shiokaze, a research-oriented fluid solver for computer graphics.
#	Created by Ryoichi Ando <rand@nii.ac.jp> on April 9, 2017. 
#
#	Permission is hereby granted, free of charge, to any person obtaining a copy of
#	this software and associated documentation files (the "Software"), to deal in
#	the Software without restriction, including without limitation the rights to use,
#	copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the
#	Software, and to permit persons to whom the Software is furnished to do so,
#	subject to the following conditions:
#
#	The above copyright notice and this permission notice shall be included in all copies
#	or substantial portions of the Software.
#
#	THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED,
#	INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A
#	PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
#	HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF
#	CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE
#	OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
#
def build(bld):
#	
	if bld.use_opengl:
		source_files = ['ui.cpp','graphics_gl.cpp']
	else:
		source_files = 'ui.cpp'
	#
	bld.shlib(source = source_files,
			target = bld.get_target_name(bld,'ui'),
			cxxflags = ['-DSPATIAL_DIM=2','-Wno-deprecated-declarations'],
			use = bld.get_target_name(bld,'core'),
			lib = bld.LIB_OPENGL+['boost_date_time'],
			framework = bld.FRAMEWORK_OPENGL)
	#
	bld.shlib(source = 'camera3.cpp',
			target = bld.get_target_name(bld,'camera3'),
			use = bld.get_target_name(bld,'core'))
	#
	bld.shlib(source = 'camera2.cpp',
			target = bld.get_target_name(bld,'camera2'),
			use = bld.get_target_name(bld,'core'))