#!/usr/bin/env python
#
#   parallel/wscript
#
#   This is part of Shiokaze, a research-oriented fluid solver for computer graphics.
#   Created by Ryoichi Ando <rand@nii.ac.jp> on March 6, 2018.
#
#	Permission is hereby granted, free of charge, to any person obtaining a copy of
#	this software and associated documentation files (the "Software"), to deal in
#	the Software without restriction, including without limitation the rights to use,
#	copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the
#	Software, and to permit persons to whom the Software is furnished to do so,
#	subject to the following conditions:
#
#	The above copyright notice and this permission notice shall be included in all copies
#	or substantial portions of the Software.
#
#	THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED,
#	INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A
#	PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
#	HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF
#	CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE
#	OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
#
import sys
#
def build(bld):
#
	bld.shlib(source = 'stdthread.cpp',
			target = bld.get_target_name(bld,'stdthread'),
			use = bld.get_target_name(bld,'core'))
#
#	TBB is currently compilable for macOS
#
	if sys.platform == 'darwin':
		bld.shlib(source = 'tbbthread.cpp',
				target = bld.get_target_name(bld,'tbbthread'),
				lib = ['tbb'],
				use = bld.get_target_name(bld,'core'))
#
	bld.shlib(source = 'sequential_splitter.cpp',
			target = bld.get_target_name(bld,'sequential_splitter'),
			use = bld.get_target_name(bld,'core'))
#
	bld.shlib(source = 'dispersed_splitter.cpp',
			target = bld.get_target_name(bld,'dispersed_splitter'),
			use = bld.get_target_name(bld,'core'))