#!/usr/bin/env python
#
#   modules/src/octree/wscript
#
#   This is part of Shiokaze fluid solver, a research-oriented fluid solver designed for collaborative projects.
#   Created by Ryoichi Ando <rand@nii.ac.jp> on April 10, 2017. All rights reserved.
#   Unauthorized use, redistributing and copying of this file, via any medium are strictly prohibited.
#
def greeting(opt):
	pass
#
def options(opt):
	greeting(opt)
#
def configure(conf):
	pass
#
def build(bld):
	#
	bld.shlib(source = 'octree2.cpp',
			target = bld.get_target_name(bld,'octree2'),
			cxxflags = ['-DSPATIAL_DIM=2'],
			use = bld.get_target_name(bld,'core'))
	#
	bld.shlib(source = 'octree3.cpp',
			target = bld.get_target_name(bld,'octree3'),
			cxxflags = ['-DSPATIAL_DIM=3'],
			use = bld.get_target_name(bld,'core'))