#!/usr/bin/env python
#
#	shared_wscript
#
#	This is part of Shiokaze, a research-oriented fluid solver for computer graphics.
#	Created by Ryoichi Ando <rand@nii.ac.jp> on 30 Jan, 2017. All rights reserved.
#
#	Permission is hereby granted, free of charge, to any person obtaining a copy of
#	this software and associated documentation files (the "Software"), to deal in
#	the Software without restriction, including without limitation the rights to use,
#	copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the
#	Software, and to permit persons to whom the Software is furnished to do so,
#	subject to the following conditions:
#
#	The above copyright notice and this permission notice shall be included in all copies
#	or substantial portions of the Software.
#
#	THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED,
#	INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A
#	PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
#	HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF
#	CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE
#	OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
#
import glob, os
#
def get_env(ctx):
	TYPE = os.path.basename(ctx.path.abspath()).replace('shiokaze-','')
	MODULES = [ path.replace(TYPE+"/", "") for path in glob.glob(TYPE+'/src/*/')]
	RESOURCES = []
	LOCAL = []
	if os.path.exists(TYPE+'/local/wscript'):
		LOCAL.append('local')
	for dir in glob.glob(TYPE+'/resources/*/'):
		if os.path.exists(dir+'wscript'):
			RESOURCES.append(dir.replace(TYPE+"/", ""))
	return TYPE, MODULES, RESOURCES, LOCAL
#
def build(bld):
	TYPE, MODULES, RESOURCES, LOCAL = get_env(bld)
	bld.set_build_env(bld,TYPE)
	bld.recurse(MODULES+RESOURCES+LOCAL)